Fix compilation issue for createFileSystemWatcher #196
monaco-languageclient: src/vscode-api.ts(52,11): error TS2740: Type '{
createFileSystemWatcher(globPattern: GlobPattern, ignoreCreateEvents:
boolean | undefined, ignoreChangeEvents: boolean | undefined,
ignoreDeleteEvents: boolean | undefined): FileSystemWatcher; ... 21 more
...; name: undefined; }' is missing the following properties from type
'typeof workspace': fs, workspaceFile, onWillCreateFiles,
onDidCreateFiles, and 4 more.

Signed-off-by: Aurélien Pupier <apupier@redhat.com>