Update Language Client to 6.0.0 #196
- requires upgrade of TtypeScript to 3.7.5 to avoid "error TS1086: An
accessor cannot be declared in an ambient context.
"
- requires API updates:
-- client/src/monaco-language-client.ts createMessageTransports now
using Promise instead of Thenable
-- vscode-uri Uri has been renamed URI
-- registerCallHierarchyProvider has moved from workspace to languages

remaining:
monaco-languageclient: src/vscode-api.ts(52,11): error TS2740: Type '{
createFileSystemWatcher(globPattern: GlobPattern, ignoreCreateEvents:
boolean | undefined, ignoreChangeEvents: boolean | undefined,
ignoreDeleteEvents: boolean | undefined): FileSystemWatcher; ... 21 more
...; name: undefined; }' is missing the following properties from type
'typeof workspace': fs, workspaceFile, onWillCreateFiles,
onDidCreateFiles, and 4 more.
monaco-languageclient: src/vscode-api.ts(209,17): error TS2322: Type
'(arg0: Uri, arg1: readonly Diagnostic[] | undefined) => void' is not
assignable to type '{ (uri: Uri, diagnostics: readonly Diagnostic[] |
undefined): void; (entries: readonly [Uri, readonly Diagnostic[] |
undefined][]): void; }'.


Signed-off-by: Aurélien Pupier <apupier@redhat.com>